set_property PACKAGE_PIN W5 [get_ports clk]	
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {segments[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]
set_property PACKAGE_PIN W6 [get_ports {segments[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property PACKAGE_PIN U8 [get_ports {segments[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property PACKAGE_PIN V8 [get_ports {segments[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property PACKAGE_PIN U5 [get_ports {segments[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property PACKAGE_PIN V5 [get_ports {segments[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property PACKAGE_PIN U7 [get_ports {segments[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]

set_property PACKAGE_PIN U2 [get_ports {digit_rota_n[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit_rota_n[0]}]
set_property PACKAGE_PIN U4 [get_ports {digit_rota_n[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit_rota_n[1]}]
set_property PACKAGE_PIN V4 [get_ports {digit_rota_n[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit_rota_n[2]}]
set_property PACKAGE_PIN W4 [get_ports {digit_rota_n[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit_rota_n[3]}]

##Buttons
set_property PACKAGE_PIN T18 [get_ports btn_up]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn_up]
set_property PACKAGE_PIN W19 [get_ports btn_left]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn_left]
set_property PACKAGE_PIN T17 [get_ports btn_right]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn_right]
set_property PACKAGE_PIN U17 [get_ports btn_down]						
	set_property IOSTANDARD LVCMOS33 [get_ports btn_down]

## SW1
set_property PACKAGE_PIN U18 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]  

set_property PACKAGE_PIN U16     [get_ports {led0}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led0}]


set_property PACKAGE_PIN P3     [get_ports {contador_activo[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {contador_activo[0]}]
set_property PACKAGE_PIN N3     [get_ports {contador_activo[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {contador_activo[1]}]
set_property PACKAGE_PIN P1     [get_ports {contador_activo[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {contador_activo[2]}]
set_property PACKAGE_PIN L1     [get_ports {contador_activo[3]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {contador_activo[3]}]
